# Generated by Django 4.1.6 on 2023-03-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intapp', '0002_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caller_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('emial', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('date', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='contacting_form',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
