# Generated by Django 4.1.6 on 2023-03-03 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intapp', '0003_caller_request_alter_contacting_form_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caller_request',
            old_name='emial',
            new_name='email',
        ),
    ]
